CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(32) NOT NULL,
    project VARCHAR(255)
);

CREATE TABLE task_activities (
    task_id BIGINT NOT NULL,
    activity VARCHAR(255),
    CONSTRAINT fk_task_activities_task FOREIGN KEY (task_id) REFERENCES tasks (id)
);
