CREATE TABLE users_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    photo VARCHAR(1000),
    CONSTRAINT uk_users_entity_email UNIQUE (email)
);

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    organization_id BIGINT,
    CONSTRAINT fk_projects_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE TABLE user_organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    organization_id BIGINT,
    role VARCHAR(32),
    status VARCHAR(32),
    CONSTRAINT fk_user_organizations_user
        FOREIGN KEY (user_id) REFERENCES users_entity (id),
    CONSTRAINT fk_user_organizations_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uk_user_organizations_user_org UNIQUE (user_id, organization_id),
    CONSTRAINT chk_user_organizations_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
    CONSTRAINT chk_user_organizations_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED'))
);

CREATE TABLE project_users (
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_project_users PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_project_users_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_users_user
        FOREIGN KEY (user_id) REFERENCES users_entity (id)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(32),
    finished_at TIMESTAMP(6),
    project_id BIGINT,
    user_id BIGINT,
    CONSTRAINT fk_tasks_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id) REFERENCES users_entity (id),
    CONSTRAINT chk_tasks_status
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED'))
);

CREATE TABLE task_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    task_id BIGINT,
    CONSTRAINT fk_task_history_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE INDEX idx_projects_organization_id ON projects (organization_id);
CREATE INDEX idx_user_organizations_user_id ON user_organizations (user_id);
CREATE INDEX idx_user_organizations_organization_id ON user_organizations (organization_id);
CREATE INDEX idx_project_users_user_id ON project_users (user_id);
CREATE INDEX idx_tasks_project_id ON tasks (project_id);
CREATE INDEX idx_tasks_user_id ON tasks (user_id);
CREATE INDEX idx_tasks_status ON tasks (status);
CREATE INDEX idx_task_history_task_id ON task_history (task_id);
