CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(9) NOT NULL,
    icon VARCHAR(64) NOT NULL,
    organization_id BIGINT NOT NULL,
    CONSTRAINT fk_categories_organization
        FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT uk_categories_org_name UNIQUE (organization_id, name)
);

CREATE INDEX idx_categories_organization_id ON categories (organization_id);

ALTER TABLE tasks ADD COLUMN category_id BIGINT;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_category
    FOREIGN KEY (category_id) REFERENCES categories (id);

CREATE INDEX idx_tasks_category_id ON tasks (category_id);
