quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:timetrack}
quarkus.datasource.password=${DB_PASSWORD:timetrack}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/timetrack}

%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:beetask;DB_CLOSE_DELAY=-1
%dev.quarkus.hibernate-orm.database.generation=update

quarkus.flyway.migrate-at-start=false
quarkus.hibernate-orm.database.generation=validate

# Swagger & OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.always-include=true

# JWT Security
mp.jwt.verify.issuer=https://beetech.net
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
