quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=https://task.beetech.dev
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With
quarkus.http.cors.credentials=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:beetask}
quarkus.datasource.password=${DB_PASSWORD:beetask}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/beetask}

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate

# Swagger & OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-health.root-path=status

# JWT Security
mp.jwt.verify.issuer=${MP_JWT_VERIFY_ISSUER}
smallrye.jwt.sign.key=${SMALLRYE_JWT_SIGN_KEY}
mp.jwt.verify.publickey=${MP_JWT_VERIFY_PUBLICKEY}

